/// Flutter icons NavBarIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavBarIcons
///      fonts:
///       - asset: fonts/NavBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavBarIcons {
  NavBarIcons._();

  static const _kFontFam = 'NavBarIcons';
  static const String? _kFontPkg = null;

  static const IconData nestafar = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ride = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burger = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fuel = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mileage = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engine = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
